# Broker MQTT para dispositivos Shelly
#persistence true
#persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Autenticación (opcional pero recomendador)
allow_anonymous true
#password_file /mosquitto/config/passwd

# Escuchar en todas las interfaces
listener 1883 0.0.0.0

# WebSocket para dashboards
listener 9001 0.0.0.0
protocol websockets
allow_anonymous true

# Optimizado para Shelly
retain_available false
#max_queued_messages 1000
